name: repeaters
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - matplotlib
  - numpy
  - geopy
  - cartopy
  - obspy
  - scipy
  - jupyter
  - scikit-learn
  - seaborn
  - shapely
  - utm